spring.application.name=letsgogolfing
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.sql.init.mode=always

bbconfig.apiKey=${BB_API_KEY}
bbconfig.projectId=${BB_PROJECT_ID}
bbconfig.baseUrl=https://api.browserbase.com/v1
bbconfig.email=${BB_EMAIL}
bbconfig.password=${BB_PASSWORD}

golfnow.email=${GOLFNOW_EMAIL}
golfnow.password=${GOLFNOW_PASSWORD}
golfnow.baseUrl=https://www.golfnow.com
golfnow.endpoints.tee-time-results=/api/tee-times/tee-time-results

aws.ses.accessKey=${AWS_ACCESS_KEY}
aws.ses.secretKey=${AWS_SECRET_KEY}
aws.ses.fromEmail=${AWS_FROM_EMAIL}
aws.ses.fromName=${AWS_FROM_NAME}
aws.ses.region=${AWS_REGION}

spring.temporal.connection.target=local
spring.temporal.start-workers=true
spring.temporal.workersAutoDiscovery.packages=com.hooswhere.letsgogolfing

stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}
